#!/bin/bash

# The first arg provided here will be used as command option
COMMAND=$1

function build_containers {
    echo "Creating containers..."
    docker-compose build
}

case $COMMAND in
  setup)
    build_containers

    echo "Running mix deps.get to configure project dependencies..."
    docker-compose run api mix deps.get
    echo "Done."
  ;;

  build)
    build_containers
    echo "Done."
  ;;

  create)
    echo "Preparing database..."
    docker-compose run api mix ecto.create
    echo "Done"
  ;;

  start)
    echo "Starting all containers..."
    docker-compose up
    echo "Done"
  ;;

  console)
    docker-compose run api iex -S mix phx.server
    echo "Finished"
  ;;

  # Default option, display help information
  *)
    echo "Invalid option. The allowed ones are:"
    echo "setup      - Setup the phoenix project"
    echo "create     - Create the hangman database"
    echo "run        - Run the hangman server"
    echo "console    - Run the hangman console"
  ;;
esac
